# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/_lang.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import _folium , _userSetting


class Ui_MainWindow(object):

    def select_(self , lang):

        _userSetting._setting._lang = lang
        self.ui = _folium.Folium_map()
        self.ui.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(766, 318)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget , clicked = lambda : self.select_("en"))
        self.pushButton.setGeometry(QtCore.QRect(270, 180, 231, 91))
        self.pushButton.setStyleSheet("font: 28pt \"Calibri\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget , clicked = lambda : self.select_("jp"))
        self.pushButton_2.setGeometry(QtCore.QRect(20, 180, 231, 91))
        self.pushButton_2.setStyleSheet("font: 28pt \"標楷體\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget , clicked = lambda : self.select_("zh-tw"))
        self.pushButton_3.setGeometry(QtCore.QRect(520, 180, 231, 91))
        self.pushButton_3.setStyleSheet("font: 28pt \"標楷體\";\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 70, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionService = QtWidgets.QAction(MainWindow)
        self.actionService.setObjectName("actionService")
        self.actionSetting = QtWidgets.QAction(MainWindow)
        self.actionSetting.setObjectName("actionSetting")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Taipei Public Transportation Recommendation Service"))
        self.pushButton.setText(_translate("MainWindow", "English"))
        self.pushButton_2.setText(_translate("MainWindow", "日本語"))
        self.pushButton_3.setText(_translate("MainWindow", "繁體中文"))
        self.label.setText(_translate("MainWindow", "Select Language"))
        self.actionService.setText(_translate("MainWindow", "Service"))
        self.actionSetting.setText(_translate("MainWindow", "Setting"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
