# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/_lang.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import _userSetting , _folium


class Ui_MainWindow(object):

    def select_(self , lang):

        _userSetting._setting._lang = lang
        self.ui = _folium.Folium_map()
        self.ui.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 318)
        MainWindow.setStyleSheet("")
        #MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        #MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget , clicked = lambda : self.select_("en"))
        self.pushButton.setGeometry(QtCore.QRect(270, 180, 231, 91))
        self.pushButton.setStyleSheet("font: 28pt \"Calibri\";\n"
"background-color: rgba(0, 0, 0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color:rgba(0,0,0,230);\n"
"padding-bottom:7px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget , clicked = lambda : self.select_("jp"))
        self.pushButton_2.setGeometry(QtCore.QRect(20, 180, 231, 91))
        self.pushButton_2.setStyleSheet("font: 28pt \"標楷體\";\n"
"background-color: rgba(0, 0, 0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color:rgba(0,0,0,230);\n"
"padding-bottom:7px;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget ,
                                                  clicked = lambda : self.select_("zh-tw"))
        self.pushButton_3.setGeometry(QtCore.QRect(520, 180, 231, 91))
        self.pushButton_3.setStyleSheet("font: 28pt \"標楷體\";\n"
"background-color: rgba(0, 0, 0,0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105,118,132,255);\n"
"color:rgba(0,0,0,230);\n"
"padding-bottom:7px;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 70, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 28pt \"Calibri\";\n"
"background-color: rgba(0, 0, 0,0);\n"
"border:none;\n"
"color:rgba(0,0,0,230);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 761, 301))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.517, y1:0.505682, x2:0.512, y2:1, stop:0 rgba(194, 194, 194, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:40px;")
        self.widget.setObjectName("widget")
        self.widget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionService = QtWidgets.QAction(MainWindow)
        self.actionService.setObjectName("actionService")
        self.actionSetting = QtWidgets.QAction(MainWindow)
        self.actionSetting.setObjectName("actionSetting")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Taipei Public Transportation Recommendation Service"))
        self.pushButton.setText(_translate("MainWindow", "English"))
        self.pushButton_2.setText(_translate("MainWindow", "日本語"))
        self.pushButton_3.setText(_translate("MainWindow", "繁體中文"))
        self.label.setText(_translate("MainWindow", "Select Language"))
        self.actionService.setText(_translate("MainWindow", "Service"))
        self.actionSetting.setText(_translate("MainWindow", "Setting"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
